### ISSUE TITLE
Module Not Found CTT

### ISSUE THREAD

**Issue by yambanis** [mila-iqia/COVI-AgentSim#100]
I'm trying to run the example simulation, but I get the following error:

from ctt.inference.infer import InferenceEngine
ModuleNotFoundError: No module named 'ctt'

I'm running on a clean virtual env after only installing COVI-AgentSim.
Python 3.8.10, ubuntu

Executed commands were as follows:

```
python3 -m pip install -e COVI-AgentSim/
python -m covid19sim.run tune=True intervention=no_intervention n_people=1000 simulation_days=30
```

**Comment by pg2455** [comment]
@nasimrahaman  - Do you know if the `ctt` module ships with this repo or is it separate?

@yambanis  - Sorry you are facing this issue. That library is intended for our machine learning repo which is separate from this repo. We had to make it optional, but I think we overlooked this issue. @mweiss17 or @nasimrahaman  : Can we make `ctt` optional in this repo?

**Comment by pg2455** [comment]
@yambanis  - Can you install COVI-ML module from here: https://github.com/mila-iqia/COVI-ML/tree/littlecrunch? 
`ctt` module is available through it.
