### ISSUE TITLE
Current message passing system is not reproducible (probably, only for heuristic)

### ISSUE THREAD

**Issue by plstcharles** [mila-iqia/COVI-AgentSim#3]
Originally: issue #105 on COVI-Canada. Opened by @pg2455 on 2020/06/19.

If you put the following code snippet just above the line https://github.com/Covi-Canada/simulator/blob/develop/src/covid19sim/base.py#L231.
```python
        with open("1.txt", "a") as f:
            f.write(f"{len(update_messages)}\n")
```

Replace 1.txt with 2.txt between two runs for 
```
python run.py tune=True n_people=100 seed=10 init_percent_sick=0.05 INTERVENTION_DAY=5 tracing_method=heuristicv1 simulation_days=20
```
Entries in `1.txt` are not the same as `2.txt`. It means that there is a problem with reproducibility somewhere. 

This is important to debug the number of update messages being not equal to the total number of past contact messages.

**UPDATES**
 - It is still reproducible for bdt, oracle, and unmitigated scenarios.
 - `City.rng` produces same sequence until the end implying that somewhere `human.rng` is changing its course.
- Using 
```python
return [human.rng.randint(0,15)]* human.rng.randint(0,14)
```
just above https://github.com/Covi-Canada/simulator/blob/develop/src/covid19sim/interventions.py#L631
makes it reproducible. 

This probably means that indeterminism has to do with computation of risks in `compute_risk` of heuristic or the way the return value from the function is handled.

**Comment by teganmaharaj** [comment]
I believe that this was resolved; @mweiss17 ?

**Comment by mweiss17** [comment]
Yes, I believe it has been. For future readers, it'd be nice to have a test for this! A quick extension of https://github.com/mila-iqia/COVI-AgentSim/blob/master/tests/test_reproducibility.py would suffice
