### ISSUE TITLE
No module named 'ctt'

### ISSUE THREAD

**Issue by dorofeevv** [mila-iqia/COVI-AgentSim#98]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [y ] I am running the latest version
- [y ] I checked the documentation and found no answer
- [y] I checked to make sure that this issue has not already been filed

# Expected Behavior

I try to run 'python -m covid19sim.run tune=True intervention=no_intervention n_people=1000 simulation_days=30' after installing covid19sim package

# Current Behavior

Error: "No module named 'ctt'"
I can not find 'ctt' package for python 3.7.4. I've found only this package: https://github.com/bmartins/python-ctt, but it hasn't any InferenceEngine

# Failure Information

"lib/python3.7/site-packages/covid19sim/inference/server_utils.py", line 23, in <module>
    from ctt.inference.infer import InferenceEngine
ModuleNotFoundError: No module named 'ctt'"

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Installing covid19sim package
2. Trying to launch simulation
3. Error: "No module named 'ctt'"

## Failure Logs

lib/python3.7/site-packages/covid19sim/inference/server_utils.py", line 23, in <module>
    from ctt.inference.infer import InferenceEngine
ModuleNotFoundError: No module named 'ctt'

**Comment by nasimrahaman** [comment]
Hi @dorofeevv, `ctt` is our machine-learning code-base. We are in the process of making that dependency optional, but in the mean time you may `pip install git+https://github.com/mila-iqia/COVI-ML.git`. 

I'm closing this issue for now, but please reopen if the problem persists.
